import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/PublicNavbar/page";
import Footer from "./Component/footer/page";
import FooterWrapper from "./Component/FooterWrapper";
import ConditionalNavbar from "./Component/ConditionalNavbar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Providers from "./provider";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
});

export const metadata: Metadata = {
  title: "Bumkampung Tuah Negeri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon/logo1.png" sizes="256x256"/>
      </head>
      <body className={poppins.className}>
        <main className="relative overflow-hidden">
          <Providers>{children}</Providers>
          <ToastContainer position="top-right" autoClose={5000} />
        </main>

      </body>
    </html>
  );
}
